name: Build APK
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest
      options: --user root
    steps:
      - uses: actions/checkout@v4

      - name: Fix permissions and build
        run: |
          chown -R root:root /github/home /__w
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Gestor360-APK
          path: bin/*.apk
